### PR TITLE
JDG-1200 - Minor fixes on cdi-jdg readme

### PR DESCRIPTION
**Pull request by zhostasa**

### CODE REVIEW

**Comment by mgencur** [comment]
Is there a related JIRA? It should be part of the commit message.

**Comment by zhostasa** [comment]
Like that?

**Comment by mgencur** [comment]
JDG-XXX Message ...
Like all commits in Infinispan.

**Comment by zhostasa** [comment]
Sorry about that

**Comment by mgencur** [comment]
NP. Looks good. Merging.

**Pull request merged**
