### PR TITLE
Add aggregations and continuous query demo

### PR DESCRIPTION
**Pull request by anistor**

### CODE REVIEW

**Comment by anistor** [comment]
It works with 1.6 too. I have reverted that pom change.

**Comment by mgencur** [comment]
Thanks @anistor . Sorry for bothering but the readme file also mentions 1.7 as a requirement :)  I suppose you want to intergrate for JDG 6.6

**Comment by anistor** [comment]
Oh, forgot to undo that. Done now.

**Comment by mgencur** [comment]
Integrated into jdg-6.6.x branch. Thanks @anistor 
I added one small commit that prevents warnings when the server starts. Tested.

**Comment by anistor** [comment]
Thanks @mgencur !

**Pull request closed without merging**
