### PR TITLE
fixes #138

### LINKED ISSUE #138: mvn clean package jboss-as:deploy does not work with suggested maven configuration
`mvn clean package jboss-as:deploy` does not work with suggested maven configuration. 

to work properly the following was used instead:

`mvn clean package jboss:deploy`

### PR DESCRIPTION
**Pull request by slaskawi**
https://github.com/jboss-developer/jboss-jdg-quickstarts/issues/138

### CODE REVIEW

**Comment by mgencur** [comment]
What does changing the version to 7.7 bring? Just curious. Is it for some newer version of EAP?

**Comment by ghost** [comment]
I just noticed that each module uses different version. So I picked up the
latest and made all equal. Tested with EAP 6.4.

**Comment by mgencur** [comment]
Pushed. Thanks! Just changed the commit message a little bit.

**Comment by slaskawi** [comment]
Thanks Martin!

**Pull request closed without merging**
