### PR TITLE
JDG 1200 - README

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/JDG-1200

### CODE REVIEW

**Comment by karesti** [comment]
@slaskawi I saw you are the author of the quickstart, you might know

**Comment by slaskawi** [comment]
@karesti I believe you can remove those lines. They are not valid anymore.

Just to give you some context - A while ago, this Quickstart could operate in two modes - as a library (added to a WAR) or by depending on JDG modules. After @wfink clarified that modules are preferred way of using our bits, I reworked the quickstart and seems I forgot to remove those lines from `READ.ME`.

**Comment by karesti** [comment]
@slaskawi thank you ! it seemed to me outdated, like something left by mistake, but I wanted to make sure ! Cool I remove it then !

**Comment by rigazilla** [comment]
merged thanks!

**Pull request merged**
