### PR TITLE
Minor corrections for wrong CLI commands and Beta versions of JDG modules

### PR DESCRIPTION
**Pull request by wfink**

### CODE REVIEW

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
Hey @wfink @mgencur @tristantarrant !

Sorry for the mess with CI in this Pull Request (Teamcity builds master branch and JDG Jenkins builds jdg-6.4.x). 

Everything seems fine - should I merge it (manually)?

Thanks!

**Comment by wfink** [comment]
from my point of view, yes please

**Comment by slaskawi** [comment]
Integrating

**Comment by slaskawi** [comment]
Hey @wfink ! 
Unfortunately there is a merge conflict. Could you please rebase it?

**Comment by wfink** [comment]
rebased and fix some minor issues

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request merged**
