### PR TITLE
ISPN-3654 Moved CDI quickstart from infinispan-quickstarts

### PR DESCRIPTION
**Pull request by slaskawi**
Hey!

This is a backport of CDI Quickstart into the product repo.

Thanks
Sebastian

### CODE REVIEW

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
retest this please

**Comment by slaskawi** [comment]
Needs new versions after ER2 is out

**Comment by mgencur** [comment]
Actually, this PR contains 3 commits. Are they all needed? I suppose the update to 6.3.0.ER2 was already integrated. What about the other one related to Fuse?

**Comment by slaskawi** [comment]
@mgencur Yes, we do need them, but good point - they should be issued as a separate PR. Thanks for the review.

**Comment by mgencur** [comment]
NP, let me know when I can try it and integrate.

**Comment by slaskawi** [comment]
@mgencur Comments implemented. Everything should be up to date and ready for integration.

**Comment by mgencur** [comment]
Integrated. Thanks:)

**Pull request closed without merging**
