### PR TITLE
Addition of quickstart : camel-jbossdatagrid-fuse

### PR DESCRIPTION
**Pull request by vchintal**

### CODE REVIEW

**Comment by slaskawi** [comment]
test this please

**Comment by vbchin2** [comment]
Need some help here understanding the next steps. Looking at the log it is clearly complaining about version 6.3.0.DR1-redhat-1 missing from redhat-earlyaccess-repository-group for about 7 projects not including mine. Since these existing before my commits I am wondering how the builds succeeded on prior commits ? Sorry I am a bit confused with all this so any help is appreciated.

**Comment by slaskawi** [comment]
Hey @vchintal ! 
I'm trying to fix CI, please don't bother about my further comments. I'll remove them as soon as I'm done.
Thanks!

**Comment by slaskawi** [comment]
Hey @vchintal !
I managed to fix the CI, it should be ok now.
Thanks!

**Comment by mgencur** [comment]
Integrated in jdg-6.5.x branch. Thanks @vchintal ! It's a very nice quickstart. I've squashed all commits into one, you're still the author:)

**Pull request closed without merging**
