### PR TITLE
ISPN-4953 Review quickstart README metadata to optimize it for the Go…

### PR DESCRIPTION
**Pull request by mgencur**
…ogle search

I've also renamed the "CDI" quickstart to "cdi-jdg", similar to helloworld-jdg because having just "CDI" is too general and might be confused with other products.

The next step for JDG 7 is to fix all the versions in readme files, and also requirements (e.g. required Java version). I'll work on that later.

### CODE REVIEW

**Comment by Holmistr** [comment]
@mgencur Regarding the mentioned next step for JDG 7, FYI https://github.com/jboss-developer/jboss-jdg-quickstarts/pull/100 contains all changes that are needed for quickstarts to migrate to ISPN 8 and WildFly 9.0.1.Final, it might be useful for you :)

**Comment by mgencur** [comment]
@Holmistr thanks! We will use that.

**Comment by mgencur** [comment]
Updated for EAP7. I've also renamed cdi to cdi-jdg so as to prevent confusion with other cdi quickstarts from other products. I was not able to fully test the quickstart due to existing issues such as https://issues.jboss.org/browse/JDG-6 or https://issues.jboss.org/browse/JDG-7

**Comment by mgencur** [comment]
And thanks @Holmistr !, I've used a lot from your previous PR.

**Pull request merged**
