### PR TITLE
KeyCloak integration for secure-embedded-cache quickstart

### PR DESCRIPTION
**Pull request by mgencur**
This is to demonstrate the integration with KeyCloak. This will be supported with JDG 7.3

### CODE REVIEW

**Comment by galderz** [comment]
Looks good @mgencur. If this is only for JDG 7.3+, shouldn't we create a jdg-7.3.x branch and send the PR there?

**Comment by mgencur** [comment]
@galderz , yes, I sent it here because the 7.3 branch didn't exist. If someone creates the branch I can send the PR there.

**Comment by galderz** [comment]
@mgencur I've just created the branch

**Comment by mgencur** [comment]
Thanks, @galderz . Created https://github.com/jboss-developer/jboss-jdg-quickstarts/pull/208 for 7.3 branch. And closing this one.

**Pull request closed without merging**
