### PR TITLE
Jdg 6.6.x - camel-jbossdatagrid-fuse update

### PR DESCRIPTION
**Pull request by tqvarnst**
Some mayor improvements to the camel-jbossdatagrid-fuse quickstart where we use camel-jbossdatagrid as a consumer and instead of user polling for content the content is at create time pushed to a websocket.

### CODE REVIEW

**Comment by mgencur** [comment]
Are the last two commits same as the previous two? I'm confused how this happened. It might be better to merge them or remove the last two. WDYT?

**Comment by mgencur** [comment]
Hi Thomas, I did a quick review and it looks good. There are just typos and minor problems. Now I'm going to try it.

**Comment by slaskawi** [comment]
@tqvarnst Could you please rebase it? Apart from that looks nice!

**Comment by tqvarnst** [comment]
Just did an push it to my repo. The Pull request should soon pick it up.

**Comment by tqvarnst** [comment]
I did a mistake in the local repo. I'll fix it and push it again.

**Comment by mgencur** [comment]
Looking...

**Comment by tqvarnst** [comment]
That is a local file that is directly under camel-jbossdatagrid-fuse directory. I can update the README.md to link to it if that makes sense?

**Comment by mgencur** [comment]
Hi Thomas, thanks. Yes, we need to make clear that index.html is a local file. This is pretty uncommon and I was confused a bit. So I think users will be confused as well. Two more minor things: 
1) there's an image in the readme file saying "cp best-footballplayers-2015.csv $incomingFolderPath/" . This seems to be redundant because because we also mention this instruction in plain text right before it. Please remove the image
2) The index.html contains this text: "a table will be appear", please change to "a table will appear"

Otherwise the quickstart work fine. I tried that and I'm ready to integrate once you do the changes. Thanks

**Comment by mgencur** [comment]
Thomas. It looks good to me. I had to do two changes: remove the terminal-1.png file and rebase on jdg-6.6.x branch. This PR is now integrated in jdg-6.6.x branch. Closing...

**Comment by mgencur** [comment]
Thanks! Nice enhancements to the quickstart.

**Pull request closed without merging**
