### PR TITLE
Spring quickstart

### PR DESCRIPTION
**Pull request by slaskawi**
Hey!

This is a backport of Spring integration quickstart.

Thanks
Sebastian

### CODE REVIEW

**Comment by slaskawi** [comment]
Needs new versions after ER2 is out

**Comment by mgencur** [comment]
Otherwise this quickstart looks nice and works well :) Let me know what you think about my comments. Thanks

**Comment by slaskawi** [comment]
@mgencur Thanks for the review. Very good comments, I'll add necessary modifications shortly.

**Comment by slaskawi** [comment]
Comments implemented. I also had to create `web.xml` because of https://access.redhat.com/solutions/1211203

**Comment by mgencur** [comment]
Integrated. Thanks!

**Pull request closed without merging**
