### PR TITLE
BZ1150949 + infinispan.xml migrated to ISPN 7

### PR DESCRIPTION
**Pull request by Holmistr**

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @Holmistr !
Sorry it took me so long to setup the CI server. Could you please remind me whether we agreed to put those tests in separate Maven profile? Currently they are causing failures in TeamCity.
Thanks!

**Comment by Holmistr** [comment]
Hi @slaskawi ,
according to discussion here https://github.com/jboss-developer/jboss-jdg-quickstarts/pull/59 , we agreed to create a separate -ci profile. I probably forgot to reflect this also into this PR, so repushed with -ci profile.

**Comment by slaskawi** [comment]
Integrating

**Comment by slaskawi** [comment]
Integrated, thanks @Holmistr !

**Pull request closed without merging**
