### PR TITLE
Fix broken link to configure Maven

### PR DESCRIPTION
**Pull request by ALRubinger**

### CODE REVIEW

**Comment by mgencur** [comment]
Hi @ALRubinger , the readme file is supposed to be used from JDF web pages such as this one: http://developers.redhat.com//quickstarts/datagrid/helloworld-jdg/index.html
The link works there. Apart from that, all the other quickstarts use the same approach and this PR fixes only one. Let me ask @sgilda what she thinks about it.

**Comment by slaskawi** [comment]
@ALRubinger @sgilda @mgencur What's the status of this PR?

**Comment by slaskawi** [comment]
@ALRubinger @sgilda @mgencur any update?

**Comment by mgencur** [comment]
I spoke with @sgilda and the latest approach is to use full links as @ALRubinger did in this PR. But this PR only fixes the helloworld quickstart. I will create another PR that fixes all quickstarts. Closing this one now. Thanks for pointing that out, @ALRubinger

**Comment by mgencur** [comment]
Replaced by https://github.com/jboss-developer/jboss-jdg-quickstarts/pull/109

**Pull request closed without merging**
