### PR TITLE
Add details about OpenShift installation, how to install and run loca…

### PR DESCRIPTION
**Pull request by gbabcan**
…l OpenShift cluster - oc cluster up

### CODE REVIEW

**Comment by karesti** [comment]
@gbabcan is there are related issue for this ?

**Comment by gbabcan** [comment]
@karesti no, there isn't created issue for this

**Comment by slaskawi** [comment]
@gbabcan +1, I really like this PR. May I suggest to add a cross reference to Cache Service documentation somewhere? You may find the docs here: https://github.com/jboss-container-images/jboss-dataservices-image/blob/dataservices-dev/documentation/cache-service.asciidoc

**Comment by gbabcan** [comment]
@slaskawi  there is already one reference, but not the direct one : [https://github.com/jboss-container-images/jboss-dataservices-image](https://github.com/jboss-container-images/jboss-dataservices-image)   But I can add this one also.

**Comment by anistor** [comment]
@gbabcan , @karesti , @slaskawi Guys, is this ready for ER4 ?

**Comment by slaskawi** [comment]
@gbabcan You know what, we will probably be changing this stuff in the future. Let's leave it as is. Integrating.

**Comment by slaskawi** [comment]
@gbabcan Thanks!

**Pull request merged**
