### PR TITLE
Complete review, upgrade to ISPN 8.0.1.Final and WildFly 9.0.1.Final

### PR DESCRIPTION
**Pull request by Holmistr**
This PR contains review of all README files, upgrade to ISPN 8.0.1.Final and WildFly 9.0.1.Final. I tried all the quickstarts and I can guarantee that all of them are fully functional.

Last thing I was thinking about, are the JDG references. I thing for "newbies" this could be quite confusing. Since we have separate branches for JDG, how about removing all JDG references from README files and substitute them with purely Infinispan references? WDYT @tristantarrant @slaskawi

### CODE REVIEW

**Comment by mgencur** [comment]
Hi Jiri, I'm sorry but most of the changes in this PR are not acceptable. The quickstarts under jboss-developer organization should refer to products. They have to mention EAP instead WildFly, JDG instead of Infinispan. Users can still download JDG or EAP through zero dolar subscription which is for development purposes only (http://www.jboss.org/terms-and-conditions/).

**Comment by mgencur** [comment]
I'm not sure what to do with our current master branch. It refers to EAP and JDG in readme files but it requires Infinispan libraries in pom.xml files. It should definitely refer to JDG in pom files as well. IMO, the master branch should be compatible with the next JDG release (6.6)  but we currently have the 6.6.x branch for this purpose.
My suggestion for the master branch would be either 
1) wait for JDG 7 DR1 and update it with dependencies on JDG 7 at that point (we could keep "master" as the name or rename to "7.0.x") or 
2) delete the master branch now, wait for JDG 7 DR1 and then create a new branch called "7.0.x"
@slaskawi @tristantarrant  WDYT?

**Comment by slaskawi** [comment]
Thanks a good question.... I wonder what other projects (like Wildfly/EAP or Camel/Fuse) do with their Quickstarts... If they drift into tutorial way (like we did with ISPN), I would say that deprecating Quickstarts and deleting master branch is fine...

**Comment by slaskawi** [comment]
We are closing master branch of this quickstarts. Having this in mind I'm closing this PR.

**Pull request closed without merging**
