### PR TITLE
JDG-1198 improves readme file

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/JDG-1198

### CODE REVIEW

**Comment by tristantarrant** [comment]
Why do we need to add it explictly ? Isn't it already a dep of infinispan-core ?

**Comment by karesti** [comment]
@tristantarrant when I build the quickstart it says that the caffeine version is missing, the parameter needs to be passes explicitly. Adding the dependency fixes that now - but I'm not sure about this correction. This is happening in two quickstarts now

**Comment by galderz** [comment]
I'm looking into this in more detail. In theory there should be no reason to add caffeine explicitly as dependency.

**Comment by slaskawi** [comment]
There was an issue when there was no Caffeine in BOM: https://issues.jboss.org/browse/ISPN-7306. Perhaps it's connected?

**Comment by galderz** [comment]
Hmmmm, I've checked out the branch in this PR and I've commented the caffeine additions. When doing that, I'm unable to replicate this when using latest `maven-settings.xml` from JDG repository, branch 7.2.x ([this one](https://github.com/infinispan/jdg/blob/jdg-7.2.x/maven-settings.xml)). See output [here](http://pastebin.test.redhat.com/516111).

If using the `settings.xml` in root of this the jboss-jdg-quickstarts does not build at all. See output [here](http://pastebin.test.redhat.com/516109).

**Comment by galderz** [comment]
Based on @slaskawi's info, I guess the issue might have been fixed in the latest JDG 7.2.x snapshot and when using the right Maven settings, it all works fine? I suspect that's what's happening here.

**Comment by galderz** [comment]
Looking at my local repo, I see this:

```
~/1/j/remote-tasks-with-streams ❯❯❯ l ~/.m2/jdg-mead-repository/org/infinispan/infinispan-bom/8.5.0-redhat-SNAPSHOT/                                             karesti_1198 ✱
total 176
drwxr-xr-x  10 g  staff   320B Sep 14 14:20 .
drwxr-xr-x   5 g  staff   160B Aug 21 15:02 ..
-rw-r--r--   1 g  staff   243B Sep 14 13:59 _remote.repositories
-rw-r--r--   1 g  staff    32K Sep 14 13:59 infinispan-bom-8.5.0-redhat-20170824.051030-4.pom
-rw-r--r--   1 g  staff    40B Sep 14 13:59 infinispan-bom-8.5.0-redhat-20170824.051030-4.pom.sha1
-rw-r--r--   1 g  staff    32K Sep 14 13:59 infinispan-bom-8.5.0-redhat-SNAPSHOT.pom
-rw-r--r--   1 g  staff   619B Sep 14 14:20 maven-metadata-jdg7-snapshots.xml
-rw-r--r--   1 g  staff    40B Sep 14 14:20 maven-metadata-jdg7-snapshots.xml.sha1
-rw-r--r--   1 g  staff   564B Aug 21 16:32 maven-metadata-local.xml
-rw-r--r--   1 g  staff   194B Sep 14 14:20 resolver-status.properties
```

The bom version is a snapshot from 20170824.051030, @karesti you'd need to see what is it being used in your case. You can pass `-X` to maven to get a debug build. This is what I see in mine (see [here](http://pastebin.test.redhat.com/516115)).

**Comment by karesti** [comment]
I can't reproduce it anymore

**Comment by galderz** [comment]
Thx @karesti, this is ready to integrate with the minor docu fix.

**Pull request merged**
