### PR TITLE
JDG-1533 - fix hotrod-endpoint-js infinispan client

### PR DESCRIPTION
**Pull request by gbabcan**
https://issues.jboss.org/browse/JDG-1533

### CODE REVIEW

**Comment by karesti** [comment]
@gbabcan you corrected this issue then ?

**Comment by karesti** [comment]
@galderz hey Galder, could you check if this is the good correction for the quickstart please ?

**Review by karesti — APPROVED** [review]

**Comment by karesti** [comment]
@gbabcan could you please amend the commits and put the the JIRA number on the commit message ? I will merge it and mark the issue as resolved then

**Comment by karesti** [comment]
@anistor I'm planing to merge this one myself once the commits are amended with the correct message. But if you are faster than me, that's fine ! 💃

**Comment by anistor** [comment]
Thanks @karesti !

**Comment by gbabcan** [comment]
@karesti commit message is updated

**Pull request merged**
