### PR TITLE
JDG-52 ModuleNotFoundException: org.infinispan:jdg-6.6 for eap-cluste…

### PR DESCRIPTION
**Pull request by mgencur**
…r-app

https://issues.jboss.org/browse/JDG-52
https://issues.jboss.org/browse/JDG-224

### CODE REVIEW

**Comment by mgencur** [comment]
Looks like the fix reveals another issue. Let's wait with this PR. I'll update it with the fix.

**Comment by mgencur** [comment]
This PR is now ready.

**Comment by mgencur** [comment]
Fixed a minor issue in Readme. Now it's ready.

**Comment by VaclavDedik** [comment]
Integrated, thanks!

**Pull request closed without merging**
