### PR TITLE
Changing hardcoded links to README.md files

### PR DESCRIPTION
**Pull request by LightGuard**
Linking to the directories of the quickstarts instead of the readme files within.

### CODE REVIEW

**Comment by slaskawi** [comment]
Hey @LightGuard @sgilda @mgencur @tristantarrant !
Could you tell me what the status of this issue is?
Everything seems fine from my point of view. Should I merge it?
Thanks!

**Comment by sgilda** [comment]
@slaskawi : The JBoss EAP quickstarts still use the relative path. For example, the https://github.com/jboss-developer/jboss-eap-quickstarts/blob/6.4.x-develop/helloworld/README.md file contains the following text that uses a relative path to link to the README file in the root of the quickstart directory: 

    See [Build and Deploy the Quickstarts](../README.md#build-and-deploy-the-quickstarts) for complete instructions and additional options._

@LightGuard : Do you have any comments?

**Comment by LightGuard** [comment]
We've since worked around this, we can drop this pr

**Comment by sgilda** [comment]
Thanks @LightGuard !

**Pull request closed without merging**
